/* 

   A) Dragable

   In order to make a container "Dragable" ( meaning that it's children
   are dragable to other containers who supports the "Dropable" feature,
   you must:
   
   1) optionally Specify in options a key-function called
      "getData", which should return a structure like:
           {
                "tooltip": "Tooltip string",   // a string that will be visible during the drag event in a tooltip following the mouse
                "data"   : <any_data_type>     // the data that is dragged
           }
   2) optionally specify in options a key called "dataType",
      reflecting the data that is dragged
   
   3) call MakeDragable( container, options );
   
   A sample options parameter:
        options = {
            "dataType": "An array of integers",
            "getData": function() {
                return {
                    "data"   : [ 1, 2, 3, 4 ],
                    "tooltip": "Moving 4 integers"
                }
            }
        }
   
   B) Dropable
   
   In order to make a container "Dropable" ( meaning that it's accepting
   data, you must:
   
   1) MakeDropable( container );
   
   2) container.addCustomEventListener( 'dragenter', function() {
        // code that gets executed when mouse enters container, in drag state
   } );
   
   3) container.addCustomEventListener( 'dragleave', function() {
        // code that gets executed when mouse leaves container in drag state
   } );
   
   4) container.addCustomEventListener( 'drop', function( data ) {
        // code that gets executed when a "drop" event is triggered.
        // the data is a object like: {
        //      "dataType":    <any> // specified on the Dragable side with MakeDragable in options.dataType
        //      "data":        <any> // generated by the options.getData().data
        //      "ownerWindow": // null, or window that contains the Dragable container
        //      "source":      // the Dragable container
        //      "event":       <event> // mouseUp event
        // }
   } );
*/

function MakeDragable( rootElement, options ) {
    
    var dragState = true;
    
    Object.defineProperty( rootElement, "isDragable", {
        "get": function( ) {
            return dragState;
        },
        "set": function( b ) {
            b = !!b;
            if (b == dragState) return;
            dragState = !!b;
            rootElement.onCustomEvent('dragable-state-change', b );
        }
    } );
    
    rootElement.onCustomEvent( 'dragable-state-change', true );
    
    options = options || {};
    
    var dragObject  = null;
    var dropTarget  = null;
    var currentTarget= null;
    var startedMove = false;
    var cssDiv = null;
    
    var tooltipDiv = null;
    
    var dragData = null;
    
    var onMouseDown = function( e ) {
        
        if (!dragState)
            return;
        
        if (e.which != 1)
            return;
        
        dragObject = null;
        dropTarget = null;
        currentTarget = null;
        dragData = null;
        startedMove = false;
        
        var dragElement = e.srcElement || e.target;

        if (dragElement == rootElement)
            return;
        
        while (dragElement.parentNode != rootElement) {
            dragElement = dragElement.parentNode;
        }
        
        dragObject = dragElement;
        
        window.addEventListener( 'mouseup', onMouseUp, true );
        window.addEventListener( 'mousemove', onMouseMove, true );

        cssDiv = document.body.appendChild( $('div') );
        cssDiv.innerHTML = '<style>* { -webkit-user-select: none !important; -moz-user-select: none !important; user-select: none !important; cursor: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABoAAAAaCAYAAACpSkzOAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAANgSURBVEiJtZVNaFxVFMd/933NJDNvXmIxGQ0thoAW7Eqh4heJoCABIWIMZBFXQoJZSEuWhQjZNYts4jJCkQZBBBdqpO5jsimFoIYSNcjkY/Jomnmx83Uz77iYN2E6TmNqJ3+4POa+c87vnnPPeQMwA5wTEc5yEY/H7yWTyRWg+yxBhmVZVjqdftl13R+VUs9yVkomk4fr6+syMDBQdl33F+C5Mylde3v735lMRorFogwODpZTqdRd4PmWg9ra2h7s7OyIiIjWWoaHh8upVOpP4FKrQflsNis1VSoVGRsb057nZYCXWtl1Bd/3pV5hGMrExIROpVK7wGstAcViseL+/r4009TU1JHrur5pmm+1AlQ6ODhoChIRmZ6ePnJd975pmoNPBHIcpxwEwSNBIiKzs7MV13VzjuN88H9Blogo0zT/NV+Li4ssLy/r2u/Ozs6k7/s3HMeJl8vlmyfNplLKBrqADmBTRB5YIoJhGMdGWmts28Z1XRYWFrTW+jvLso6BInJZKXUH+A04B6SB7obnU4CquSilbijTNI/y+bzpOA5ra2uMjo6Gq6urRjwep6enRwdBcC2fz1+PTpoE3gMuAU8D1ik/QFmjVrqVlRX6+/v1xsbG3vz8fGiaJpOTk6ZlWR8qpbzI4QrwDvDMCZAQ8IE1oBTtdSulVLi0tKRGRkZ0oVD4Umt9s6Oj44ft7e1YLpejr69PVyqV90ul0h2qfyk15YDdaGWBQ+APwBeRo6gCs1F5qydIJBIl27Y/By6ICJ7n/TQ3NxeKiAwNDZVs2/4GeBH4IlofP9S6cD7a72rYn635WIZhHGqtF7TW10VkFyCXy306MzNzu7e3N7a1tUUsFrO01ufrspGGciWoXn6XUioBiIhs1htYYRhOlMvlWyJy7ziKyK+e5309Pj5+WUQywC1gq/EylFJvABepNscrwGdRCQvAJw+BgK8kyrNeQRB8FATBC0AR2AMuNNoA7wJOZOMD3wK3gb8aDa1mkCgrAdbrTt/M5lr07iLVGfpZRH5vFu+0c/Bf2gHuUs2KaBzSQOyJQdGld0UB08B94KpSqrseECnzOKD6Er8KvH5Kvwrw/eOANql2UxtgnGCXpzrAtWFeFZE99YheaCql1JvA21RL5jcEzAJZETls5vsPIkD9la0zK5IAAAAASUVORK5CYII=) 0 0, auto !important; }</style>';
    };
    
    var stopListening = function() {
        window.removeEventListener( 'mouseup', onMouseUp, true );
        window.removeEventListener( 'mousemove', onMouseMove, true );
    }
    
    var onMouseUp = function( e ) {
        if (cssDiv) {
            cssDiv.innerHTML = '';
            cssDiv.parentNode.removeChild( cssDiv );
            cssDiv = null;
        }
        
        if (tooltipDiv !== null) {
            document.body.removeChild( tooltipDiv );
            tooltipDiv = null;
        }
        
        if (startedMove === false) {
            stopListening();
            return; //it was jus a click
        }
        
        /* Propagate the drop event through the whole dom tree until the document.body */
        // console.log( "Stop dragging",  window.dropEvent = e, dragObject );

        stopListening();
        
        var target = e.toElement || e.target;
        
        var dropData = {
            "ownerWindow"   : getOwnerWindow( rootElement ),
            "source"        : rootElement,
            "dataType"      : options.dataType || null,
            "data"          : (dragData && dragData.data ) ? dragData.data : dragObject,
            "event"         : e
        };
        
        while ( target != document.body.parentElement ) {
            try {
                if (target.isDropable) {
                    target.onCustomEvent( 'dragleave' );
                    if ( target.onCustomEvent( 'drop', dropData ) )
                        return;
                }
            } catch (silent){ }
    
            target = target.parentNode;
        }
    
        dragObject = null;
    };
    
    var onMouseMove = function( e ) {
        if ( dragObject === null )
            return; //this should not happen, but hey...
    
        if ( startedMove == false)  {
            startedMove = true;

            if (options.getData) {
                dragData = options.getData();
                // console.log( "DragData: ", dragData );
            } else dragData = null;

            /* console.log( "started to drag: ", dragObject ); */
            rootElement.onCustomEvent( 'dragstart', {
                "node": dragObject
            } );
            
            if (dragData && dragData.tooltip) {
                tooltipDiv = document.body.appendChild( 
                    $('div', 'DOMDragDropTooltip')
                );
                tooltipDiv.innerHTML = dragData.tooltip;
            }
        }
    
        if (tooltipDiv !== null) {
            var xy = getMousePos( e );
            var xe = getXY( e.toElement || e.target );
            // console.log( xe[0] + xy.X, xe[1] + xy.Y );
            tooltipDiv.style.left = xe[0] + xy.X + 10 + 'px';
            tooltipDiv.style.top = xe[1] + xy.Y - 2 - tooltipDiv.offsetHeight + 'px';
        }
    
        var destination = e.toElement || e.target;
    
        if (destination != currentTarget) {

            //console.log( 'destination: ', destination );

    
            var found = false;
    
            var dropData = {
                "ownerWindow"   : getOwnerWindow( rootElement ),
                "source"        : rootElement,
                "dataType"      : options.dataType || null,
                "data"          : (dragData && dragData.data ) ? dragData.data : dragObject,
                "event"         : e
            };
            
            /* Determine the drop target */
            while ( destination != document.body.parentElement ) {

                if (destination.isDropable) {
                    if ( destination != dropTarget ) {
                        if (dropTarget !== null) {
                            try {
                                dropTarget.onCustomEvent('dragleave', dropData );
                            } catch (silent) {
                                console.error("Dropable::dragleave:: Exception: " + silent );
                            }
                        }
                        dropTarget = destination;
                        try {
                            dropTarget.onCustomEvent( 'dragenter', dropData );
                        } catch (silent) {
                            console.error("Dropable::dragenter:: Exception: " + silent );
                        }

                    }
    
                    found = true;
                    break;
                }
                
                destination = destination.parentNode;
            }

            if (found == false) {
                if (dropTarget !== null) {
                    try {
                        dropTarget.onCustomEvent('dragleave');
                    } catch (silent) {}
                }
                dropTarget = null;
            }
        
            currentTarget = destination;
        
        }
    
    };
    
    rootElement.addEventListener( 'mousedown', onMouseDown, true );
    
}

function MakeDropable( element, options ) {
    
    options = options || {};
    
    var isDropable = true;
    
    Object.defineProperty( element, "isDropable", {
        "get": function() {
            return isDropable;
        },
        "set": function( boolVal ) {
            boolVal = !!boolVal;
            if (boolVal == isDropable) return;
            isDropable = boolVal;
            element.onCustomEvent( 'dropable-state-change', boolVal );
        }
    });
    
    if ( options.dragInElements ) {
        
        (function() {
            
            var currentElement = null;
            
            var onMouseMove = function( e ) {
                var item = e.srcElement || e.target;
                
                while ( item.parentNode != element ) {
                    item = item.parentNode;
                    if (item == document.documentElement)
                        return;
                }
                
                if (item != currentElement) {
                    if (currentElement != null) {
                        element.onCustomEvent( 'dragmove-out', currentElement );
                    }
                    currentElement = item;
                    element.onCustomEvent( 'dragmove-in', currentElement );
                }
            };
            
            element.addCustomEventListener( 'dragenter', function() {
                currentElement = null;
                element.addEventListener( 'mousemove', onMouseMove, true );
                return true;
            } );
            
            element.addCustomEventListener( 'dragleave', function() {
                element.removeEventListener( 'mousemove', onMouseMove, true );
            } );
            
        })();
        
    }
    
    element.onCustomEvent( 'dropable-state-change', true );
}

function MakeSortable( holder ) {
    
    EnableCustomEventListeners( holder );
    
    var pos;
    
    if ( ( pos = getComputedStyle( holder ).position ) != 'relative' ) {
        console.warn("MakeSortable(", holder , "): It seems that position is not relative, but '" + pos + "'" );
    }
    
    var swapDom = function( a, b ) {
        a.swapWith(b);
    };
    
    
    var makeDragable = function( item ) {

        item.setAttribute('dragable', 1 );

        var theClone = null;
        
        var oldStyle;
        
        var dontOverlap = function( a, b ) {

            var x1 = a.offsetLeft;
            var y1 = a.offsetTop;

            var x2 = x1 + a.offsetWidth;
            var y2 = y1 + a.offsetHeight;

            var x3 = b.offsetLeft;
            var y3 = b.offsetTop;

            var x4 = x3 + b.offsetWidth;
            var y4 = y3 + b.offsetHeight;

            return ( x2 < x3 || x1 > x4 || y2 < y3 || y1 > y4 );
        }
        
        var changed = false;
        var isDragging = false;
        var dragStartTime = 0;
        
        var movedX = 0;
        var movedY = 0;
        var moved = false;
        
        var dragger = new dragObject( 
            item, item, new Position( -20000, -20000 ), new Position( 20000, 200000 ), function(ev, el) {
            
                dragStartTime = (new Date()).getTime();
                
                movedX = el.offsetLeft;
                movedY = el.offsetTop;
                moved  = false;
                
                isDragging = false;
            
                /* Dispose old clone */
                if ( theClone ) {
                    if( theClone.parentNode ) {
                        theClone.parentNode.removeChild( theClone );
                    }
                    theClone = null;
                }
            
                if (ev.which != 1) {
                    cancelEvent( ev );
                    return false;
                }
            
                theClone = item.cloneNode( true );
                theClone.style.opacity = .5;

                oldStyle = JSON.parse( JSON.stringify( getComputedStyle( item ) ) );
                
                if ( oldStyle.position != 'absolute' ) {
                    oldStyle.left= '';
                    oldStyle.top = '';
                    oldStyle.right = '';
                    oldStyle.bottom = '';
                    oldStyle.position = '';
                    oldStyle.width = item.style.width;
                    oldStyle.height= item.style.height;
                    oldStyle.display=item.style.display;
                }
                
                oldStyle.zIndex = oldStyle.zIndex == 'auto' ? '' : oldStyle.zIndex;
                
            }, function( pos, el, e ) {
                
                if ( movedX == el.offsetLeft && movedY == el.offsetTop && !moved )
                    return;
                
                moved = true;
                
                if ( !isDragging ) {
                    (function() {
                        changed = false;
                        
                        //Actually now the drag has started
                        item.style.width = item.style.width || ( item.offsetWidth + 'px' );
                        item.style.height= item.style.height || ( item.offsetHeight+ 'px' );
                        
                        item.style.display = 'block';
                        item.style.position = 'absolute';
                        item.style.zIndex = 10000000;
                        
                        item.addAfter(theClone);
                        
                        while (item.offsetHeight > theClone.offsetHeight)
                            item.style.height = ( parseInt( item.style.height ) - 1 ) + 'px';

                        while (item.offsetWidth > theClone.offsetWidth)
                            item.style.width = ( parseInt( item.style.width ) - 1 ) + 'px';

                        item.style.left = theClone.offsetLeft - holder.scrollLeft + 'px';
                        item.style.top  = theClone.offsetTop - holder.scrollTop + 'px';
                        
                        isDragging = true;
                    })();
                }
            
                item.style.position = 'absolute';
                item.style.display = 'block';
                item.style.zIndex = 10000000;
                
                // Drag Run
                var found = false;
                var element = holder.firstChild;
                
                if ( ( new Date() ).getTime() - dragStartTime > 400 ) {
                    do {
                        if ( !dontOverlap( item, element ) && item != element ) {
                            found = element;
                            break;
                        }
                        if (!element.nextSibling)
                            return;
                        element = element.nextSibling;
                    } while ( true );

                    if ( found !== false && found != theClone ) {
                        theClone.swapWith( found );
                        changed = true;
                    }
                }
                
            }, function() {

                if (!isDragging)
                    return;
                    
                isDragging = false;

                item.style.width = oldStyle.width;
                item.style.height= oldStyle.height;
                
                item.style.position = oldStyle.position;
                item.style.display = oldStyle.display;
                
                item.style.left = oldStyle.left;
                item.style.top = oldStyle.top;
                item.style.right = oldStyle.right;
                item.style.bottom= oldStyle.bottom;
                
                item.style.zIndex = oldStyle.zIndex;
                
                try {
                    theClone.addBefore( item );
                } catch(e) {
                    console.warn( "Could not re-insert original item to dom: ", e );
                }

                try {
                    holder.removeChild( theClone );
                } catch (e) {
                    console.warn( e );
                }

                if (changed)
                    holder.onCustomEvent('change');
                
            }, false 
        );
    }
    
    for (var i=0; i<holder.childNodes.length; i++) {
        makeDragable( holder.childNodes[i] );
    }
    
    holder.addEventListener('DOMNodeInserted', function( e ) {
        
        var el = holder.firstChild;
        
        while ( el ) {
            if (!el.getAttribute('dragable'))
                makeDragable( el );
            el = el.nextSibling;
        }
        
    }, true );
}